import {Canvas } from '@react-three/fiber'
import Head from 'next/head'
import {AnimationProvider} from "@/context/AnimateProvider";
import {ThreeD} from "@/three";
import Progress from "@/components/Progress";
import {Stats} from "@/components/Stats";


export default function () {
  console.log("rerendering main page")
  return (
    <>
      <Head>
        <title>Chance Portfolio</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div
        style={{
          background: 'black',
          height: '100vh',
          width: '100vw',
          position: 'absolute',
          top: 0,
          left: 0,
          zIndex: -1,
        }}
      >
        <AnimationProvider>
          <Progress/>
          <Stats/>
          <Canvas>
            <ThreeD/>
          </Canvas>
        </AnimationProvider>
      </div>
    </>
  )
}
